### ISSUE TITLE
nicMSlesion_linux instead of nicMSlesion.linux

### ISSUE THREAD

**Issue by mbrown0294** [sergivalverde/nicMSlesions#1]
I believed the suggestion in the README to run the command `nicMSlesion.linux` may be a typo? As my code only worked after running 

`sh nicMSlesion_linux` with an underscore instead of a period.

Similarly, "nicMSlesion.win.bat" might be "nicMSlesion_win.bat" for Windows users.

**Comment by sergivalverde** [comment]
Done.
