### ISSUE TITLE
Target image resolution and Python environment

### ISSUE THREAD

**Issue by amandamer** [sergivalverde/nicMSlesions#17]
Hi Sergi,

I would like to know if the target image used during the transfer learning process could have non-isotropic resolution.
Another question: part of the code is written in C? Is it ok to run the code in a Python environment?

Kind regards!

**Comment by sergivalverde** [comment]
Hi @amandamer,

Theoretically you can change the  patch size to non-isotropic resolutions.
But take into account that the pre-trained model has been trained with
isotropic resolucion so the results may be weird.

The code is 100% python.

take care,
s

**Comment by amandamer** [comment]
Ah ok, thank you so much for the reply!
Do you recommend some software/tool to change the resolution of ground truth images?
