### ISSUE TITLE
Overfitting during retraining

### ISSUE THREAD

**Issue by letilessa** [sergivalverde/nicMSlesions#21]
Dear Sergi,
I full trained a model using ISBI and MICCAI dataset and got very good results. But now, I am trying to use this model for retraining the last 3 FC layers as the domain adaptation with the target images, however I am having trouble with overfitting. What would be the optimal number of epochs and patience?

Kind regards

**Comment by ghofranGh2022** [comment]
Hi @letilessa has the nicMSlesions approach been carried out with you ??, 
can you help me please, I have a lot of problems doing the training and the test like this:
Thanks.
![Capture22](https://user-images.githubusercontent.com/100536429/159658563-9ba5cf67-8bce-4dda-a1e4-6eb6c29279ae.PNG)

**Comment by sergivalverde** [comment]
Hi @ghofranGh2022 

Are you pointing the configuration options to the folder where data is? 

This looks suspicious: 

`PRE: .ipynb_checkpoints identifying input modalities`

**Comment by sergivalverde** [comment]
@letilessa Can you share your experience? Did it work for you finally?

**Comment by ghofranGh2022** [comment]
Mr.Sergi, I don't know how to do that!!, I just created a folder that contains flair, t1, lesion data, then I copied the path in the configuration file and the default file!
