### ISSUE TITLE
error into training type error : a byte -like object is required not str

### ISSUE THREAD

**Issue by ghofraneLALA** [sergivalverde/nicMSlesions#25]
hello, i need your help please, when i go to do the training, I find this error 
![Screenshot from 2022-02-26 12-54-03](https://user-images.githubusercontent.com/100683049/156148059-0df968b2-2a9e-40ed-a594-e54b9d2cc0b2.png)
![Screenshot from 2022-02-27 16-26-55](https://user-images.githubusercontent.com/100683049/156148182-2e1a04b5-2ee9-4dd1-aae8-781f7ded8c8a.png)
Can you help me please!

**Comment by sergivalverde** [comment]
Hi. 
looks like that you are using the software with Python 3.  Until we don't update the software, the required version of Python is 2.X 

Sorry for that 🙏
