### ISSUE TITLE
Running nicMSlesions in Google Colaboratory  or with other env

### ISSUE THREAD

**Issue by ghofranGh2022** [sergivalverde/nicMSlesions#27]
Hi @isabellameds @[mbrown0294](https://github.com/mbrown0294) @[isabellameds](https://github.com/isabellameds) @[colpark](https://github.com/colpark)
I need your help please about the running of the code nicMSlesions of SergiValverde
Can you help me please! Thanks.

**Comment by sergivalverde** [comment]
@ghofranGh2022 what is your actual problem?

**Comment by ghofranGh2022** [comment]
Hi @sergivalverde 
Thank you 
When i execute the file "nic_infer_segmentation_batch.py" to do the test, i find the problem: "valueError: attempt to get argmin of an empty sequence"  
The input data is CHB_train_Case which contains FLAIR, t1, T2, lesion.
I use the model pretrained baseline_2ch.
![S1](https://user-images.githubusercontent.com/100536429/159880047-4ac905a4-9ae0-4913-8c95-f21f44f43227.png)
![Sans titre36](https://user-images.githubusercontent.com/100536429/159880236-ea41c9a1-ff0b-461c-8419-4062916f81c1.png)
![Sans titre24](https://user-images.githubusercontent.com/100536429/159880413-a2d15d1e-2798-4740-9bda-6aad21a986d5.png)
![Sans titre38](https://user-images.githubusercontent.com/100536429/159881538-d7a7d987-fbc5-44c8-a794-22a3528dc3b8.png)
Thanks.

**Comment by sergivalverde** [comment]
Is your inference folder pointing to the data to infer? Looks like that it is pointing to a empty or inexistent folder.

**Comment by ghofranGh2022** [comment]
@sergivalverde  I used the data from the CHB_train_case database and I put them in a folder called images, and I copied the path of these data in the file configuration.cfg file and the default.cfg file, ?! I don't know how to make this data read by the program Mr.sergi

**Comment by sergivalverde** [comment]
If you are running the code inside a collab instance then your `inference folder` should point to (as I see in your figure): 

`/content/gdrive/MyDrive/nicMSlesions/images` 

then inside images, you should have a folder for each subject. Please see how to run it: 

https://github.com/sergivalverde/nicMSlesions#how-to-run-it

So inside `images` folder, each patient should be inside a different folder.

**Comment by ghofranGh2022** [comment]
Hello Mr.Sergi @sergivalverde first, i want to thank you,
i did this, and i put the image folder under nets/baseline_2ch folder and i did another way to organize the folders, i put it under content/drive/... , i put each patient in a folder and i put the flair, t1 and lesion (Consensus) images in these folders but i found the same problem?!! I don't know what I should do!!!!
![Sans titre](https://user-images.githubusercontent.com/100536429/160220338-14fad0ce-5be5-4a93-8ce9-095f5fd1f6d4.png)
![Sans titre45](https://user-images.githubusercontent.com/100536429/160220347-a979809e-1ba9-45f0-bf3c-6cdd643fadc3.png)
![Sans titre44](https://user-images.githubusercontent.com/100536429/160220352-21d7e56b-6fbb-4793-a04a-4f5e118c7eb3.png)
![Sans titre43](https://user-images.githubusercontent.com/100536429/160220358-b4a3da30-7492-40b1-8c46-8512a4e012f2.png)
