### ISSUE TITLE
Baseline 2-ch Network 

### ISSUE THREAD

**Issue by ste93ste** [sergivalverde/nicMSlesions#3]
On which dataset the network "Baseline 2-ch" is trained?

Is the network used in this paper?

Valverde, S., Cabezas, M., Roura, E., González-Villà, S., Pareto, D., Vilanova, J. C., … Lladó, X. (2017). Improving automated multiple sclerosis lesion segmentation with a cascaded 3D convolutional neural network approach. NeuroImage, 155, 159–168 . doi

**Comment by sergivalverde** [comment]
Hi Stefano.

The baseline 2ch is based on the MICCAI2008 and MICCAI2016 datasets. You can see it here:

https://arxiv.org/abs/1805.12415

or the final publication:

Valverde, S., Salem, M., Cabezas, M., Pareto, D., Vilanova, J. C., Ramió-Torrentà, L., … Lladó, X. (2018). One-shot domain adaptation in multiple sclerosis lesion segmentation using convolutional neural networks, Neuroimage: Clinical, 2018, 101638. doi

**Comment by ste93ste** [comment]
Perfect! thanks!
