### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by zswgzx** [sergivalverde/nicMSlesions#8]
I'm trying to perform inference using the pre-trained model, but have the following error.
 
configuration options:
 
modalities : ['FLAIR', 'T1']
fract_negative_positive : 2.0
test_folder : /path/to/testing
weight_paths : None
load_weights : True
t_bin : 0.5
min_error : 0.5
num_layers : None
max_epochs : 400
pretrained_model : baseline_2ch
image_tags : ['flair', 't1']
gpu_number : 2
denoise_iter : 3
roi_tags : ['lesion']
register_modalities : True
save_tmp : True
denoise : True
output_folder : /output
experiment : baseline_2ch
mod3_tags : ['None']
t1_tags : ['t1']
batch_size : 128
x_names : ['FLAIR_brain.nii.gz', 'T1_brain.nii.gz']
current_scan : scan
full_train : False
train_folder : /path/to/training
mod4_tags : ['None']
skull_stripping : True
net_verbose : 1
patience : 50
flair_tags : ['flair']
patch_size : (11, 11, 11)
balanced_training : False
l_min : 10
out_name : out_seg.nii.gz
min_th : 0.5
debug : True
randomize_train : True
train_split : 0.25
pretrained : None
fully_convolutional : False

DEBUG:  2
Using TensorFlow backend.
Traceback (most recent call last):
  File "nic_infer_segmentation_batch.py", line 97, in <module>
    model = cascade_model(options)
  File "/home/docker/src/libs/CNN/build_model.py", line 95, in cascade_model
    model = get_network(options)
  File "/home/docker/src/libs/CNN/nets.py", line 24, in get_network
    net_input = Input(name='in1', shape=(channels,) + options['patch_size'])
  File "/miniconda/lib/python2.7/site-packages/keras/engine/topology.py", line 1375, in Input
    input_tensor=tensor)
  File "/miniconda/lib/python2.7/site-packages/keras/engine/topology.py", line 1286, in __init__
    name=self.name)
  File "/miniconda/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 349, in placeholder
    x = tf.placeholder(dtype, shape=shape, name=name)
AttributeError: 'module' object has no attribute 'placeholder'

docker@19764b608857:~/src$ ls
__init__.py     config       nets                             utils
app.py          libs         nic_infer_segmentation_batch.py
cnn_scripts.py  logonic.png  nic_train_network_batch.py

GPU is completely new to me, so any help would be appreciated.

**Comment by zswgzx** [comment]
I have to install tensorflow 1.14.0 though because 1.6.0 seems too old?

**Comment by sergivalverde** [comment]
Hi, If you are using the docker, then you don't have to install anything apart from docker and be sure that the machine running the code has the proper nvidia-drivers and cuda. I would encourage to use this [version of nicmslesions](https://github.com/NIC-VICOROB/nic_tools):

Then go to nicmslesions and follow the instructions. It's basically using a docker file from the Docker hub and running everything from a shell script. We have this version running in several machines without problems. 

Let met know,
s

**Comment by zswgzx** [comment]
Thanks, I gave up the docker option and still had some issues as new comer.

So I followed https://www.tensorflow.org/install/gpu#ubuntu_1604_cuda_90_for_tensorflow_1130 and pip installed the tensorflow-gpu==1.6.0 & modules from requirement.txt.

When installing the required modules, tensorflow was upgraded to 2.0.0 so I did pip uninstall tensorflow-gpu-1.6.0 & tensorflow, and reinstall tensorflow-gpu1.6.0

Then I set configuration.config's gpu = Ture, gpu_number =0, and ran nic_infer_segmentation_batch.py

Does the following look fine and use the gpu?

2019-10-18 19:08:38.609022: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-10-18 19:08:38.609826: E tensorflow/stream_executor/cuda/cuda_driver.cc:406] failed call to cuInit: CUresult(-1)
2019-10-18 19:08:38.609884: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: invivo-gpu
2019-10-18 19:08:38.609900: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: invivo-gpu
2019-10-18 19:08:38.609993: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
2019-10-18 19:08:38.610052: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 410.129.0

Thanks again.

**Comment by zswgzx** [comment]
Here's output from nvidia-smi

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.129      Driver Version: 410.129      CUDA Version: ERR!     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00007196:00:00.0 Off |                  Off |
| N/A   43C    P0    73W / 149W |      0MiB / 12206MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by zswgzx** [comment]
I'm running it on Azure with NC6 virtual machine with NVIDIA Corporation GK210GL [Tesla K80] (rev a1).

The driver was downloaded as runfile NVIDIA-Linux-x86_64-384.183.run and I followed the instructions. The cuda-9-0 and others were installed in /usr/local/cuda-9.0/. But the python script nic_infer... still couldn't find the device:

modalities : ['FLAIR', 'T1']
fract_negative_positive : 2.0
test_folder : /home/szhang/nicMSlesions/images
weight_paths : None
load_weights : True
t_bin : 0.5
min_error : 0.5
num_layers : None
max_epochs : 400
pretrained_model : baseline_2ch
image_tags : ['flair', 't1']
gpu_number : 1
denoise_iter : 3
roi_tags : ['lesion']
register_modalities : True
save_tmp : True
denoise : True
output_folder : /output
experiment : baseline_2ch
mod3_tags : ['None']
t1_tags : ['t1']
batch_size : 128
x_names : ['FLAIR_brain.nii.gz', 'T1_brain.nii.gz']
current_scan : scan
full_train : False
train_folder : /path/to/training
mod4_tags : ['None']
skull_stripping : True
net_verbose : 1
patience : 50
flair_tags : ['flair']
patch_size : (11, 11, 11)
balanced_training : False
l_min : 10
out_name : out_seg.nii.gz
min_th : 0.5
debug : True
randomize_train : True
train_split : 0.25
pretrained : None
fully_convolutional : False
--------------------------------------------------
DEBUG:  1
Using TensorFlow backend.
WARNING:tensorflow:From /home/szhang/.local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py:1062: calling reduce_prod (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From /home/szhang/.local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py:2550: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From /home/szhang/.local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py:1123: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
> CNN: loading weights from baseline_2ch configuration
/home/szhang/nicMSlesions/nets/baseline_2ch/nets/model_1.hdf5
/home/szhang/nicMSlesions/nets/baseline_2ch/nets/model_2.hdf5
2019-10-19 03:32:46.719746: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-10-19 03:32:51.254096: E tensorflow/stream_executor/cuda/cuda_driver.cc:406] failed call to cuInit: CUDA_ERROR_NO_DEVICE
2019-10-19 03:32:51.254170: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: invivo-gpu
2019-10-19 03:32:51.254187: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: invivo-gpu
2019-10-19 03:32:51.254275: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: 418.87.1
2019-10-19 03:32:51.254327: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 418.87.1
2019-10-19 03:32:51.254343: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:300] kernel version seems to match DSO: 418.87.1

I was surprise to find that the CUDA version became the latest:

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.87.01    Driver Version: 418.87.01    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 0000AEA8:00:00.0 Off |                    0 |
| N/A   57C    P0    64W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

Would this be the reason and is there any work around? Thanks

**Comment by zswgzx** [comment]
It's run on NVIDIA Corporation GK210GL [**Tesla K80**] (rev a1). I installed nvidia driver **384** and **cuda-9-0** (https://www.tensorflow.org/install/gpu#ubuntu_1604_cuda_90_for_tensorflow_1130, checked with nvidia-smi). **libcudnn7=7.0.3.11-1+cuda9.0**. **cuda-repo-ubuntu1604_9.0.176-1_amd64.deb**.
 
If Docker image is NOT used, try to install the required python packages first (keras instroduced tensorflow/tensorboard2.0.0, and should be uninstalled), then install tensorflow-gpu. 

Everything looks good so far. Thanks again Sergi.
